// generated by vite-plugin-components
// read more https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    'AkarIcons:figmaFill': typeof import('virtual:vite-icons/akar-icons/figma-fill')['default']
    'AntDesign:apiOutlined': typeof import('virtual:vite-icons/ant-design/api-outlined')['default']
    'AntDesign:html5Outlined': typeof import('virtual:vite-icons/ant-design/html5-outlined')['default']
    'AntDesign:twitterCircleFilled': typeof import('virtual:vite-icons/ant-design/twitter-circle-filled')['default']
    'Bx:bxlGit': typeof import('virtual:vite-icons/bx/bxl-git')['default']
    'Bx:bxsFileJson': typeof import('virtual:vite-icons/bx/bxs-file-json')['default']
    'Carbon:logoGithub': typeof import('virtual:vite-icons/carbon/logo-github')['default']
    'Carbon:overflowMenuHorizontal': typeof import('virtual:vite-icons/carbon/overflow-menu-horizontal')['default']
    'Ci:hamburger': typeof import('virtual:vite-icons/ci/hamburger')['default']
    'Cib:adobePhotoshop': typeof import('virtual:vite-icons/cib/adobe-photoshop')['default']
    'Cib:mailRu': typeof import('virtual:vite-icons/cib/mail-ru')['default']
    'Cib:netlify': typeof import('virtual:vite-icons/cib/netlify')['default']
    'Cib:vueJs': typeof import('virtual:vite-icons/cib/vue-js')['default']
    'Cib:wordpress': typeof import('virtual:vite-icons/cib/wordpress')['default']
    'Codicon:terminalCmd': typeof import('virtual:vite-icons/codicon/terminal-cmd')['default']
    'FaSolid:laptopCode': typeof import('virtual:vite-icons/fa-solid/laptop-code')['default']
    'FileIcons:typescript': typeof import('virtual:vite-icons/file-icons/typescript')['default']
    'FileIcons:vite': typeof import('virtual:vite-icons/file-icons/vite')['default']
    'Ion:logoPwa': typeof import('virtual:vite-icons/ion/logo-pwa')['default']
    'La:tools': typeof import('virtual:vite-icons/la/tools')['default']
    'Mdi:translate': typeof import('virtual:vite-icons/mdi/translate')['default']
    Nav: typeof import('./src/components/Nav.vue')['default']
    Overlay: typeof import('./src/components/Overlay.vue')['default']
    'Ri:npmjsLine': typeof import('virtual:vite-icons/ri/npmjs-line')['default']
    'Teenyicons:firebaseOutline': typeof import('virtual:vite-icons/teenyicons/firebase-outline')['default']
    'Teenyicons:javascriptOutline': typeof import('virtual:vite-icons/teenyicons/javascript-outline')['default']
    'Uil:html3Alt': typeof import('virtual:vite-icons/uil/html3-alt')['default']
  }
}

export { }
